config/routes.rb
Ticketee::Application.routes.draw do

devise_for :users , :controllers => { :registrations => "registrations" } do
  get '/awaiting_confirmation',
  :to => "users#confirmation",
  :as => 'confirm_user'
  get '/users/sign_out' => 'devise/sessions#destroy' 
end

put '/admin/users/:user_id/permissions',
    :to => 'admin/permissions#update',
    :as => :update_user_permissions

resources :projects do
  resources :tickets
end

root :to => "projects#index"

namespace :admin do
  root :to => "base#index"
  resources :users do
    resources :permissions
  end
end


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true
  has_many :tickets, :dependent => :delete_all
  has_many :permissions, :as => :thing
  scope :readable_by, lambda {|user| joins(:permissions).where(:permissions => {:action => "view",
  																				 :user_id => :user.id})}

def self.for(current_user)
	if current_user.admin?
    Project
  else
    Project.readable_by(current_user)
  end
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authorize_admin!, :except => [:index, :show]
	before_filter :authenticate_user!, :only => [:index, :show]
	before_filter :find_project, :only => [:show, :edit, :update, :destroy]

def find_project
	@project = Project.for(current_user).find(params[:id])
	rescue ActiveRecord::RecordNotFound
	flash[:alert] = "The project you were looking for could not be found"
	redirect_to root_path
end

def index
	@projects = Project.for(current_user).all
end

def new
	@project = Project.new
end

def create
	@project = Project.new(params[:project])
	if @project.save
		flash[:notice] = "Project has been created"
		redirect_to @project
	else
		flash[:alert] = "Project has not been created"
		redirect_to :action => "new"
	end
end

def show
end

def edit
end

def update
	if @project.update_attributes(params[:project])
		flash[:notice] = "Project has been updated"
		redirect_to @project
	else
		flash[:alert] = "Project has not been updated"
		redirect_to :action => "edit"
	end
end

def destroy
	@project.destroy
	flash[:notice] = "Project has been deleted"
	redirect_to projects_path
end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<ul>
<%= @projects.each do |project| %>
<li><%= link_to project.name, project %></li>
<% end %>
</ul>
<% admins_only do %>
<%= link_to "New Project", new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h2>New project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title "Sublime - Projects - Ticketee" %>
<h2><%= @project.name %></h2>
<%= admins_only do %>
<%= link_to "New Project", new_project_path %>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project", @project, :method => :delete, 
									    									:confirm => "Are you sure you want to delete this project?" %>
<% end %>
<%= link_to "New Ticket", new_project_ticket_path(@project) %>
<ul id='tickets'>
<% @project.tickets.each do |ticket| %>
<li>
#<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
</li>
<% end %>
</ul>