config/routes.rb
Ticketee::Application.routes.draw do

devise_for :users , :controllers => { :registrations => "registrations" } do
  get '/awaiting_confirmation',
  :to => "users#confirmation",
  :as => 'confirm_user'
  get '/users/sign_out' => 'devise/sessions#destroy' 
end

put '/admin/users/:user_id/permissions',
    :to => 'admin/permissions#update',
    :as => :update_user_permissions

resources :projects do
  resources :tickets
end

root :to => "projects#index"

namespace :admin do
  root :to => "base#index"
  resources :users do
    resources :permissions
  end
end


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<nav>
	<%= admins_only do %>
	<%= link_to "Admin", admin_root_path %><br>
<% end %>
<% if user_signed_in? %>
	Signed in as <%= current_user.email %>
	<%= link_to "Log out", destroy_user_session_path %>
<% else %>
	<%= link_to "Sign in", new_user_session_path %>
	<%= link_to "Sign up", new_user_registration_path %>
<% end %>
</nav>
<body>
<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
	<%= value %>
</div>
<% end %>
<h1><%= link_to "Ticketee", root_path %></h1>
<%= yield %>

</body>
</html>